version: '3'
services:
  scoresup-ai:
    image: "ekholabs/deeplearning-stack"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "dl-workshop"
    working_dir: "/dl-workshop"
    volumes:
      - .:/dl-workshop
    expose:
      - "8888"
    ports:
      - "8888:8888"
